# Generated by Django 3.0.5 on 2021-05-24 20:35

from django.db import migrations, models
import djongo.models.fields
import user_details.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('login', models.CharField(max_length=200)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('node_id', models.CharField(max_length=200)),
                ('avatar_url', models.CharField(max_length=200)),
                ('gravatar_id', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('html_url', models.CharField(max_length=200)),
                ('followers_url', models.CharField(max_length=200)),
                ('following_url', models.CharField(max_length=200)),
                ('gists_url', models.CharField(max_length=200)),
                ('starred_url', models.CharField(max_length=200)),
                ('subscriptions_url', models.CharField(max_length=200)),
                ('organizations_url', models.CharField(max_length=200)),
                ('repos_url', models.CharField(max_length=200)),
                ('events_url', models.CharField(max_length=200)),
                ('received_events_url', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('site_admin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReposDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', djongo.models.fields.ArrayField(model_container=user_details.models.Owner)),
            ],
        ),
    ]
